'use server';
/**
 * @fileOverview Generates a comprehensive tagging report based on SEO analysis.
 *
 * - generateTaggingReport - A function that generates the tagging report.
 * - GenerateTaggingReportInput - The input type for the generateTaggingReport function.
 * - GenerateTaggingReportOutput - The return type for the generateTaggingReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTaggingReportInputSchema = z.object({
  seoReport: z.any().describe('The SEO report generated by the SEO Analyzer Agent.'),
  scrapJson: z.any().describe('The original scrap JSON generated by the Scraping Agent.'),
});
export type GenerateTaggingReportInput = z.infer<typeof GenerateTaggingReportInputSchema>;

const GenerateTaggingReportOutputSchema = z.object({
  report: z.string().describe('The Markdown / structured JSON report.'),
  readyToExport: z.string().describe('A ready_to_export version suitable for rendering in PDF.'),
});
export type GenerateTaggingReportOutput = z.infer<typeof GenerateTaggingReportOutputSchema>;

export async function generateTaggingReport(input: GenerateTaggingReportInput): Promise<GenerateTaggingReportOutput> {
  return generateTaggingReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTaggingReportPrompt',
  input: {schema: GenerateTaggingReportInputSchema},
  output: {schema: GenerateTaggingReportOutputSchema},
  prompt: `You are an expert in SEO and web analytics. You will generate a comprehensive tagging report based on the SEO analysis and the original website structure.

SEO Report:
{{seoReport}}

Original Scrap JSON:
{{scrapJson}}

Your report should include the following sections:
- Overview
- Recommended events
- dataLayer structure
- Suggested GA4 mappings
- Tagging consistency summary

Generate a ready_to_export version suitable for rendering in PDF.

Ensure the report is well-structured and easy to understand.`,
});

const generateTaggingReportFlow = ai.defineFlow(
  {
    name: 'generateTaggingReportFlow',
    inputSchema: GenerateTaggingReportInputSchema,
    outputSchema: GenerateTaggingReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
