import type { Analysis } from './types';

export const analyses: Analysis[] = [
  {
    id: 'scrap_2025_10_09_001',
    url: 'https://multiplica.com',
    createdAt: '2024-07-21T10:00:00Z',
    completedAt: '2024-07-21T10:15:00Z',
    status: 'completed',
    seoScore: 89,
    recommendations: [
      'Add data-component attributes to <section> tags.',
      'Rename duplicated hero components.',
      'Ensure newsletter_form uses POST with valid consent.',
    ],
    screenshots: ['screenshot-1', 'screenshot-2', 'screenshot-3'],
    guidePdfUrl: 'https://example.com/guide.pdf',
  },
  {
    id: 'scrap_2025_10_09_002',
    url: 'https://vercel.com',
    createdAt: '2024-07-20T14:30:00Z',
    completedAt: null,
    status: 'in_progress',
    seoScore: null,
    recommendations: [],
    screenshots: [],
    guidePdfUrl: null,
  },
  {
    id: 'scrap_2025_10_09_003',
    url: 'https://www.apple.com',
    createdAt: '2024-07-19T09:00:00Z',
    completedAt: '2024-07-19T09:05:00Z',
    status: 'failed',
    seoScore: 34,
    recommendations: [
      'Critical: Missing H1 tag on homepage.',
      'Multiple images lack alt text.',
    ],
    screenshots: ['screenshot-4'],
    guidePdfUrl: null,
  },
  {
    id: 'scrap_2025_10_09_004',
    url: 'https://github.com',
    createdAt: '2024-07-18T18:00:00Z',
    completedAt: '2024-07-18T18:20:00Z',
    status: 'completed',
    seoScore: 95,
    recommendations: ['Ensure all interactive elements are keyboard accessible.'],
    screenshots: ['screenshot-5', 'screenshot-6'],
    guidePdfUrl: 'https://example.com/guide.pdf',
  },
    {
    id: 'scrap_2025_10_09_005',
    url: 'https://www.wikipedia.org',
    createdAt: '2024-07-17T11:00:00Z',
    completedAt: null,
    status: 'pending',
    seoScore: null,
    recommendations: [],
    screenshots: [],
    guidePdfUrl: null,
  },
];
